name: Set AWS EKS kubeconfig 
command: aws eks update-kubeconfig --region {{region}} --name {{cluster}}  --alias {{alias}}
arguments:
  - name: region
    description: AWS region of the cluster
  - name: cluster
    description: The EKS cluster name
  - name: alias 
    description: Alias for the cluster 
    

tags: ["kubeconfig"]