--- 
name: Check security issues in Symfony project dependencies 
command: symfony check:security
tags: 
  - symfony
  - php 
description: Check security issues in Symfony project dependencies
arguments: [] 
source_url: "https://symfony.com/doc/current/setup.html#checking-security-vulnerabilities" 
author: Łukasz Jakutowicz 
author_url: "https://github.com/lukaszjakutowicz"
shells: []
