---
name: Provide Vercel Environment Variables at Runtime.
command: vercel --env {{KEY1}}={{value1}} --env {{KEY2}}={{value2}}
tags:
  - vercel
description: "Provide environment variables at runtime. You can add more key like --env KEY3=value3...."
arguments:
  - name: KEY1
    description: Name of the key 1
    default_value: ~
  - name: value1
    description: Name of the value 1
    default_value: ~
  - name: KEY2
    description: Name of the key 2
    default_value: ~
  - name: value2
    description: Name of the value 2
    default_value: ~
source_url: "https://vercel.com/docs/cli#introduction/unique-options/env"
author: Umar Hadi
author_url: "https://github.com/umarhadi"
shells: []